name: mydigital_id
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  dio: ^5.3.4
  extended_image: ^8.2.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  flutter_swiper_view: ^1.1.8
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1


flutter:
  assets:
    - assets/images/
  uses-material-design: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/mydigital_id.png"